version: '2'
services:
    tezintegration-app:
        image: tezintegration
        environment:
            # - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://tezintegration-postgresql:5432/TezIntegration
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    tezintegration-postgresql:
        extends:
            file: postgresql.yml
            service: tezintegration-postgresql
